# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 445e6b12773e1a31b6fb4a7fabffe7ea8b63e76b352a3a38f67572821e152f6e5f60b890c46aa45ec3d4d8c7ef2f4a67eb9629b27a0e79bf1edc830a8ad83024

test:
  secret_key_base: ee9222acca60068ebd585598903a1609a9f49b4409d6f1520e47142c218efe476ae19766715d1f9d7120361506fbdb52e0dd903174bee20e278574c8a290b846

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
